### ISSUE TITLE
在MAC系统下安装运行出错

### ISSUE THREAD

**Issue by skyjay8** [somewheve/ctpbee#15]
出错信息如下。。。。。
/usr/local/bin/python3.7 /Users/jay/OneDrive/Python/AntQuant/CtpBee_Test/quick_start.py
Traceback (most recent call last):
  File "/Users/jay/OneDrive/Python/AntQuant/CtpBee_Test/quick_start.py", line 120, in <module>
    go()
  File "/Users/jay/OneDrive/Python/AntQuant/CtpBee_Test/quick_start.py", line 111, in go
    app.start()
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/ctpbee-0.23-py3.7-macosx-10.9-x86_64.egg/ctpbee/app.py", line 120, in start
    self._load_ext()
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/ctpbee-0.23-py3.7-macosx-10.9-x86_64.egg/ctpbee/app.py", line 96, in _load_ext
    MdApi, TdApi = self.interface.get_interface(self)
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/ctpbee-0.23-py3.7-macosx-10.9-x86_64.egg/ctpbee/interface/__init__.py", line 43, in get_interface
    return cls.load_interface(app.config.get("INTERFACE"))
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/ctpbee-0.23-py3.7-macosx-10.9-x86_64.egg/ctpbee/interface/__init__.py", line 30, in load_interface
    from ctpbee.interface.ctp import BeeTdApi, BeeMdApi
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/ctpbee-0.23-py3.7-macosx-10.9-x86_64.egg/ctpbee/interface/ctp/__init__.py", line 1, in <module>
    from .md_api import BeeMdApi
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/ctpbee-0.23-py3.7-macosx-10.9-x86_64.egg/ctpbee/interface/ctp/md_api.py", line 5, in <module>
    from .lib import *
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/ctpbee-0.23-py3.7-macosx-10.9-x86_64.egg/ctpbee/interface/ctp/lib.py", line 3, in <module>
    from ctpbee.api.ctp import *
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/ctpbee-0.23-py3.7-macosx-10.9-x86_64.egg/ctpbee/api/ctp/__init__.py", line 1, in <module>
    from .vnctpmd import MdApi
ImportError: dlopen(/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/ctpbee-0.23-py3.7-macosx-10.9-x86_64.egg/ctpbee/api/ctp/vnctpmd.cpython-37m-darwin.so, 2): Symbol not found: __ZN15CThostFtdcMdApi15CreateFtdcMdApiEPKcbb
  Referenced from: /Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/ctpbee-0.23-py3.7-macosx-10.9-x86_64.egg/ctpbee/api/ctp/vnctpmd.cpython-37m-darwin.so
  Expected in: flat namespace
 in /Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/ctpbee-0.23-py3.7-macosx-10.9-x86_64.egg/ctpbee/api/ctp/vnctpmd.cpython-37m-darwin.so

**Comment by somewheve** [comment]
等待官方放出基于mac的ctp  API ，当前情况下无法解决改常见问题 ，参见海风的 pyctp的issue区
